mojio-sdk-rest/src/main/java/io/moj/java/sdk/Query.java

NOTE: "select" is not yet implemented on the API.

Remove $ from pagination query parameters, as per PT-131

---

mojio-sdk-rest/src/main/java/io/moj/java/sdk/MojioClient.java
mojio-sdk-rest/src/main/java/io/moj/java/sdk/MojioStorageApi.java
mojio-sdk-rest/src/test/java/io/moj/java/sdk/MojioClientTest.java

MB-258: Added MojioStorageAPI file with calls

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/Location.java
mojio-sdk-model/src/test/java/io/moj/java/sdk/model/values/LocationTest.java
mojio-sdk-model/src/test/java/io/moj/java/sdk/model/values/ValueTests.java
mojio-sdk-rest/src/main/java/io/moj/java/sdk/MojioAuthApi.java
mojio-sdk-test/src/main/java/io/moj/java/sdk/test/TestUtils.java

* Removed Location.Time field
* Changed getters/setters for Location.Timestamp fields to use Long
* Made Location.Status a String (server currently sending a comma-separated list of statuses, discussing with Platform to at least make this a GPSStatus[])

Location model updates to match API

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/push/Observer.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/push/Transport.java
mojio-sdk-rest/src/main/java/io/moj/java/sdk/MojioPushApi.java

* Added DELETE endpoints for observers
* Added GET, POST, and DELETE endpoints for observer transports
* Fixed bug where Observer.Throttle and Timestamp were being parsed as Timestamps instead of Timespans.

Updates to observer API

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/response/MessageResponse.java
mojio-sdk-rest/src/main/java/io/moj/java/sdk/MojioRestApi.java

* Created endpoint for adding user emails
* Added ModelState to MessageResponse (changes to this are pending but for now this matches the API's response)
* Removed double-annotated endpoints (unclear what actually happens)

Created endpoint for adding user emails

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/utils/TimeUtils.java

Using this in Motion to normalize timestamps before writing to the database so they sort properly as Strings

Refactored some timestamp parsing functionality into public TimeUtils.normalizeTimestamp()

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/Trip.java

New Trip properties are going to be exposed for IdlingCount/HarshAccelCount/HarshDecelCount so states don't have to be queried.

AD-492 Add IdleCount/HarshAccelCount/HarshDecelCount to Trip model.

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/stream/ObjectType.java
mojio-sdk-model/src/test/java/io/moj/java/sdk/model/stream/ObjectTypeTest.java

Adding a new object type: "Note".

AD-717: Adding “Note” to ObjectType for T-Mobile Service Messages.

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/Geofence.java
mojio-sdk-model/src/test/java/io/moj/java/sdk/model/GeofenceStateTest.java

Updated the Geofence model according to https://1mojio.atlassian.net/browse/PT-1367
Followed the Transaction enum example.
Will update databasehelper version and SDK version after this is merged.

AD-817: Updated Geofence model

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/Vehicle.java

AD-940: Missed adding the new CompatDetails to Vehicles earlier.

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/Mojio.java

AD-2095: Adding Deleted field to Mojios.

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/Trip.java

PA-2773 [Driver score] Implement driver scoring integration

PA-2773 [Driver score] Implement driver scoring integration

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/stream/Settings.java

Doing this to support both camel case and pascal case. Also, this model should be backwards compatible with V2 as well.

PA-4089: Support V3 notification settings

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/stream/ObjectType.java
mojio-sdk-model/src/test/java/io/moj/java/sdk/model/stream/ObjectTypeTest.java

Updates `ObjectType` to add `BatteryPredictiveMaintenance` and `AirFilterPredictiveMaintenance`
`model/stream/ObjectType.java`
Have to wait for https://1mojio.atlassian.net/browse/PA-5326
Lots of failing tests (😢 ) but the ones for this feature are passing

PA-5326 - Predictive Maintenance Object Types

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/Vehicle.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/PredictiveMaintenance.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/PredictiveWarning.java

[PA-5322 Predictive Maintenance - Context Cards](https://1mojio.atlassian.net/browse/PA-5322)
This changes are required for Mykhaylo work.

PA-5322 Predictive Maintenance - Context Cards

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/Vehicle.java

Added a new object called RealOdometer.

TDE-2619 add support for real odometer

---

mojio-sdk-model/build.gradle
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/EngineOil.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/EngineOilTemperature.java
mojio-sdk-rest/build.gradle

Updates for retrofit in gradle, updates for EngineOil and EngineOilTemperature models

Updates for retrofit in gradle, updates for EngineOil and EngineOilTemperature models

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/MojioEnvironment.java

PA-6262: Supporting custom environment.
This PR is to simply remove unused environments to give the Environment Switcher more space for editable URLs.

PA-6262 custom url

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/Trip.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/Details.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/Properties.java

PA-6193 [Biz Expensing] Integration with platform
https://1mojio.atlassian.net/browse/PA-6193
PA-6167 [Biz Expensing] New Timeline Card View + Trip Tags/Text
https://1mojio.atlassian.net/browse/PA-6167
Added trip details to Trip model.
Reviewer should start at io.moj.java.sdk.model.Trip

PA-6193 [Biz Expensing] Integration with platform

---

mojio-sdk-rest/src/main/java/io/moj/java/sdk/auth/AuthInterceptor.java

PA-6284: Added constant for "No access token".

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/enums/RiskSeverity.java
mojio-sdk-model/src/test/java/io/moj/java/sdk/model/enums/RiskSeverityTest.java

https://1mojio.atlassian.net/browse/PA-7295
added a new value "Critical" to RiskSeverity
RiskSeverity enum

PA-7295 - added a new value "Critical" for RiskSeverity

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/stream/Settings.java

Added LowFuelActivityMode. Values: "Low", "Intelligent"
Doc - https://1mojio.atlassian.net/wiki/spaces/AR/pages/1338703873/Intelligent+Fueling

PA-7443 [Intelligent Fueling Recommendations] Notification Settings

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/Mojio.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/Vehicle.java

https://1mojio.atlassian.net/browse/PA-7407
Added vehicleType and mojioType parameters to support motion free. This helps us to detect if a vehicle is obd/virtual/bluetooth. Based upon type of vehicle we have to use different api's to delete or add vehicle.

PA-7407: [Motion Free]Added vehicleType and mojioType for verify virtual vehicle

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/HybridBattery.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/HybridEngine.java

PA-7622 add alternative keys to parse entities received from WebSockets

PA-7622 add alternative keys to parse entities received from WebSockets

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/enums/BrakeFluidLevelWarningType.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/stream/Settings.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/BrakeFluid.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/CompletedOdometer.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/DistanceToNextService.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/NextService.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/TimeToNextService.java

https://1mojio.atlassian.net/browse/PA-7668
adjusted BrakeFluid and NextService models
https://github.com/mojio/mojio-java-sdk/pull/170

PA-7668 updated models for MR1

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/Vehicle.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/stream/ObjectType.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/FuelCapacity.java
mojio-sdk-model/src/test/java/io/moj/java/sdk/model/stream/ObjectTypeTest.java
mojio-sdk-model/src/test/java/io/moj/java/sdk/model/values/ValueTests.java

Added new Object types basing on https://1mojio.atlassian.net/wiki/spaces/AR/pages/1338703873/Intelligent+Fueling:
For the three notification variations mentioned above, there are three corresponding object types
IntelligentFuelSavedAndRecommendedFillup
IntelligentFuelRecommendedFillup
IntelligentFuelNotRecommendedFillup

PA-7652 [Intelligent Fueling Recommendations] Notify user if they filled up gas at the station we recommended

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/Vehicle.java

PA-7764 [Intelligent Fueling Recommendations] Fuel Tank Capacity in Vehicle Profile (Edit Car) screen

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/VehicleProperties.java
mojio-sdk-model/src/main/java/io/moj/java/sdk/model/values/VehicleStatus.java

💥 Crashlytics crash
https://console.firebase.google.com/project/mojio-phoenix/crashlytics/app/android:io.moj.mobile.android.motion.dteu/issues/96ac1075bf1787487ace5c2939bb3b28
⁉️ What does this PR do?
Fixes crash of Battery status click from dashboard

FIXING CRASH DUE TO SERIALIZABLE IMPLEMENTATION IN NEWLY INTRODUCED CLASSES

---

mojio-sdk-model/src/main/java/io/moj/java/sdk/model/stream/ObjectType.java
mojio-sdk-model/src/test/java/io/moj/java/sdk/model/stream/ObjectTypeTest.java

https://1mojio.atlassian.net/browse/PA-8023
added new notification type

PA-8023 added new notification object type
